name: MobMoney
main: com.anderhurtado.spigot.mobmoney.MobMoney
version: 5.1.6
author: Anonymous_Dr
description: Kill mobs to get money.
depend: [Vault]
softdepend:
 - CrackShot
 - MyPet
 - MythicMobs
 - LevelledMobs
 - ProtocolLib
 - PlaceholderAPI
 - AuraMobs
api-version: 1.13
commands:
 mobmoney:
  description: Plugin''s command.
  aliases: [mb]
permissions:
 mobmoney.reload:
  description: Give's permission to reload the config.
  default: op
 mobmoney.disableworld:
  description: Give's permission to disable a world.
  default: op
 mobmoney.enableworld:
  description: Give's permission to enable a world.
  default: op
 mobmoney.get:
  description: Give's permission to get money killing mobs.
  default: true
 mobmoney.toggle:
  description: Give's permission to toggle the message received at kill a entity to get money.
  default: true
 mobmoney.temporalMultiplier:
   description: Allows the user to view the available time of the multiplier
   default: true
 mobmoney.temporalMultiplier.set:
  description: Allows the user to set the temporal multiplier
  default: op